services:
  consul:
    image: "hashicorp/consul:1.20.1"
    hostname: "consul"
    command: "agent -dev -client 0.0.0.0"
    networks:
      - vault
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    volumes:
      - ./backups:/backups:rw
      - ./config/consul/acls/:/consul/config/acls:ro
      - ./config/consul:/config:ro
      - ./certs:/certs:ro
  vault:
    depends_on:
      - consul
    image: "hashicorp/vault:1.18.1"
    hostname: "vault"
    links:
      - "consul:consul"
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: https://127.0.0.1:8200
      VAULT_CACERT: /certs/ca.crt
    networks:
      - vault
    ports:
      - "8200:8200"
    volumes:
      - ./config/vault:/config:z
      - ./config/vault/policies:/policies:z
      - ./certs:/certs:z
      - ./tools/wait-for-it.sh:/wait-for-it.sh:z
      - ./audit:/audit:z
    entrypoint: /wait-for-it.sh -t 20 -h consul -p 8500 -s -- vault server -config=/config/vault.hcl
networks:
  vault:
    driver: bridge
